CREATE TABLE IF NOT EXISTS Tasks(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT,
    due_date DATETIME,
    reminder BOOLEAN NOT NULL DEFAULT 0,
    is_done BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Notes(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT
);

CREATE TABLE IF NOT EXISTS Tags(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Rubbish(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL,
    original_id INTEGER NOT NULL,
    deleted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);